USE [TRANSACMIF];
GO

CREATE OR ALTER VIEW dbo.vw_dwh_dim_asesor
WITH ENCRYPTION 
AS
WITH CTE_AUX_ASESOR AS (
	SELECT
		T_PRE.PERIODO AS Periodo,
		CASE
            -- 🔥 AJUSTE ESTRUCTURAL: Reemplazo de RIGHT por LIKE para identificar 1 y 2 dígitos
			WHEN T_ANA.ID_AGE = '98' THEN
				CASE
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%10' THEN '10' -- Lima SJL
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%11' THEN '11' -- Chiclayo
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%12' THEN '12' -- Arequipa
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%13' THEN '13' -- Pucallpa
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%6'  THEN '06' -- Juliaca
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%7'  THEN '07' -- Lima Los Olivos
					ELSE '98'
				END
			WHEN T_ANA.ID_AGE = '01' THEN
				CASE
					WHEN RTRIM(T_ANA.ID_USER) LIKE '%9' THEN '09' -- Magisterio
					ELSE '01' -- Wanchaq
				END
			ELSE T_ANA.ID_AGE
		END AS IdSAgencia,
		T_ANA.ID_USER AS IdSAsesor,
		T_PER.RAZON AS AsesorNombresApellidos,
		T_CAR.DESCRIP AS Cargo
	FROM PREEC T_PRE
	INNER JOIN SEGURIDAD.DBO.ANAREC T_ANA ON T_ANA.ID_ANAREC = T_PRE.ID_ANA AND T_ANA.FLAG_ANAREC = 'A'
	INNER JOIN SEGURIDAD.dbo.USUARIOS T_USU ON T_USU.ID_USER = T_ANA.ID_USER
	INNER JOIN SEGURIDAD.dbo.GRUPOUSER T_GRU ON T_GRU.ID_GRUPO = T_USU.ID_GRUPO AND T_GRU.NOM_GRUPO = 'CREDITOS'
    INNER JOIN SEGURIDAD.dbo.PERSONAL T_PER ON T_PER.DNI = T_USU.DNI
    INNER JOIN SEGURIDAD.dbo.TCARGO_USER T_CAR ON T_CAR.ID_CARGO = T_PER.ID_CARGO
	WHERE T_PRE.PERIODO = '202606'
	  AND T_PRE.SALDO_PRES > 0 
	  AND T_USU.ID_USER NOT IN (
		'PRECASTIGO', 'RJULI6', 'RJULIACA', 'RLIMA7', 'RQUILLA3', 'RSICUA4',
		'LHR5', 'HTEJ5', 'TKPN5', 'GHVJ5', 'OTA5', 'SDHF5', 'CMN5', 'HQND5'
	  )
)
SELECT DISTINCT
	T.Periodo,
	T.IdSAsesor AS CodAsesor,
	T.AsesorNombresApellidos,
    T.Cargo,
	T.IdSAgencia AS CodAgencia
FROM
	CTE_AUX_ASESOR T;
GO