CREATE OR ALTER VIEW gc_colocacion_cpp WITH ENCRYPTION AS
/*
- Sobre creditos extornados (improcedentes)
- Sobre creditos castigados
*/
WITH
CTE_AUX_COLOCACION AS (
SELECT
    T_PTM.CUENTA,
    T_PTM.OTORGA,
    T_PTM.PAGARE,
    T_USU.ID_USER,
    T_PTM.MONTO_PRESTAMO
FROM
    PRESTAMO T_PTM WITH (NOLOCK)
    INNER JOIN PREEC T_PRE WITH (NOLOCK)
        ON  T_PRE.CUENTA = T_PTM.CUENTA
        AND T_PRE.OTORGA = T_PTM.OTORGA
        AND T_PRE.PAGARE = T_PTM.PAGARE
        AND T_PRE.PERIODO = '{PERIODO_ACTUAL}'
    INNER JOIN SEGURIDAD.dbo.ANAREC T_ANA WITH (NOLOCK)
        ON  T_ANA.ID_ANAREC = T_PRE.ID_ANA
        AND T_ANA.FLAG_ANAREC = 'A'
    INNER JOIN SEGURIDAD.dbo.USUARIOS T_USU WITH (NOLOCK)
        ON  T_USU.ID_USER = T_ANA.ID_USER
    INNER JOIN SEGURIDAD.dbo.GRUPOUSER T_GRU WITH (NOLOCK)
        ON  T_GRU.ID_GRUPO = T_USU.ID_GRUPO
        AND T_GRU.NOM_GRUPO = 'CREDITOS'
WHERE
    T_PTM.TIPO_PROD <> '52'
    --- Optimización SARGable para lectura de índices por fecha
    AND T_PTM.OTORGA >= CAST('{PERIODO_ACTUAL}01' AS DATE)
    AND T_PTM.OTORGA < DATEADD(MONTH, 1, CAST('{PERIODO_ACTUAL}01' AS DATE))
)
SELECT
    CAST(T.OTORGA AS DATE) AS Fecha,
    T.ID_USER              AS IdSAsesor,
    COUNT(T.PAGARE)        AS [ColocacionNumReal],
    SUM(T.MONTO_PRESTAMO)  AS [ColocacionMontoReal]
FROM
    CTE_AUX_COLOCACION T
GROUP BY
    T.OTORGA,
    T.ID_USER