CREATE OR ALTER VIEW gc_repago_cpp WITH ENCRYPTION AS
WITH
CTE_AUX_DURACION AS (
SELECT
    T_MOV.FECHA_MOV,
    T_MOV.CUENTA,
    T_MOV.PAGARE,
    T_MOV.OTORGA,
    T_USU.ID_USER,
    T_MOV.CAPITAL
FROM
    PREMOV T_MOV WITH (NOLOCK)
    INNER JOIN PREEC T_PRE WITH (NOLOCK)
        ON  T_PRE.CUENTA = T_MOV.CUENTA
        AND T_PRE.OTORGA = T_MOV.OTORGA
        AND T_PRE.PAGARE = T_MOV.PAGARE
        AND T_PRE.PERIODO = '{PERIODO_ACTUAL}'
    INNER JOIN SEGURIDAD.dbo.ANAREC T_ANA WITH (NOLOCK)
        ON  T_ANA.ID_ANAREC = T_PRE.ID_ANA
        AND T_ANA.FLAG_ANAREC  = 'A'
    INNER JOIN SEGURIDAD.dbo.USUARIOS T_USU WITH (NOLOCK)
        ON  T_USU.ID_USER = T_ANA.ID_USER
WHERE
--- Optimización SARGable para Repagos del periodo actual
    T_MOV.FECHA_MOV >= CAST('{PERIODO_ACTUAL}01' AS DATE)
    AND T_MOV.FECHA_MOV < DATEADD(MONTH, 1, CAST('{PERIODO_ACTUAL}01' AS DATE))
--- Movimiento que no sea por apertura
    AND T_MOV.TIPO_MOV != '0001'
--- Tipo de documento: VOUCHER ING. (01), NOTA DE ABONO (03)
    AND T_MOV.TIPO_DOC IN ('01','03')
    AND NOT EXISTS (
        SELECT 1
        FROM PREMOV A WITH (NOLOCK)
        WHERE
            A.FECHA_MOV = T_MOV.FECHA_MOV AND
            A.COD_AGE   = T_MOV.COD_AGE   AND
            A.COD_CAJA  = T_MOV.COD_CAJA  AND
            A.TIPO_DOC  = T_MOV.TIPO_DOC  AND
            A.NRO_DOC   = T_MOV.NRO_DOC   AND
            LEFT(A.TIPO_MOV, 2) = '01'
    )
)
SELECT
    CAST(T.FECHA_MOV AS DATE) AS Fecha,
    T.ID_USER                 AS IdSAsesor,
    SUM(T.CAPITAL)            AS RepagoReal
FROM CTE_AUX_DURACION T
GROUP BY
    T.FECHA_MOV,
    T.ID_USER