table:
  dim:
    asesor: 'dim_asesor'
  fct:
    flow:
      day:
        calcbl: 'fct_flow_day_calcbl'
        manubl: 'fct_flow_day_calcbl'
      month:
        manubl: 'fct_flow_month_manubl'
    stock:
      month:
        calcbl: 'fct_stock_month_calcbl'
