GO
CREATE OR ALTER VIEW gc_duracion WITH ENCRYPTION
AS

WITH CTE AS (

SELECT
    --ID del asesor
    NEXO_ANA.ID_USER,
    --Promedio de plazo
    AVG(P.PLAZO) AS PRO_PLAZO,
    --Varios
    SUM(PD.CAPITAL) AS VARIOS,
    --Numero de operaciones
    (SELECT COUNT(PAGARE) FROM PREEC WHERE OTORGA>='01/09/2025' AND ID_ANA=E.ID_ANA) AS NUM_OPE,
    --"Operacion de division"
    (
        SUM(PD.CAPITAL) /
        (SELECT COUNT(PAGARE) FROM PREEC WHERE OTORGA>='01/09/2025' AND ID_ANA=E.ID_ANA)
    ) AS OPE_DIV
FROM
    PREEC                     E
    INNER JOIN SEGURIDAD.DBO.ANAREC NEXO_ANA ON NEXO_ANA.ID_ANAREC = E.ID_ANA AND NEXO_ANA.FLAG_ANAREC = 'A'
    INNER JOIN PRESTAMO       P  ON P.PAGARE=E.PAGARE AND P.OTORGA >= '01/09/2025'
    INNER JOIN PRE_DEDUCESOLI PD ON P.PAGARE = PD.NRO_SOL AND GLOSA =  'Cursos-Capacitación'
WHERE
    PERIODO='202509'
GROUP BY
    E.ID_ANA,
    NEXO_ANA.ID_USER

)

SELECT
    FORMAT(GETDATE(), 'yyyyMM') AS Periodo,
    T.ID_USER AS IdSAsesor,
    (T.OPE_DIV / 5) AS Duracion
FROM CTE T

GO
